Citizen.CreateThread(function()
	AddTextEntryByHash(GetHashKey('DOMINATOR31'), "Dominator GTX")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_1'), "White Stripes")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_2'), "Black Stripes")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_3'), "White Stripes with side labels")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_4'), "Black Stripes with side labels")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_5'), "White Stripes v2")
	AddTextEntryByHash(GetHashKey('DOM31_LIV_6'), "Black Stripes v2")
end)